### ISSUE TITLE
Some items in media search results are returning wrong data

### ISSUE THREAD

**Issue by eraychumak** [Spimy/Subtitles#11]
Some items are returning as `null` and some are missing property values like `imdb_id`

**Replicating**

Searching `a quiet place` would result in one of the items being `null`.

Searching `spiderman` would result in item `9` titled `Spider-Man vs. Doc Ock` returning an empty `imdb_id`.

**Comment by Spimy** [comment]
Some entries in TMDB seem to not have an `imdb_id`. I will not return items with no `imdb_id` property.
